class PostsController < ApplicationController
  #def index
# #11 declare instance var @posts and assign it a collection of Post objects
#using all method provided by ActiveRecord. all returns a collection of Post objects
	#@posts = Post.all
	#@posts.each_with_index do |post, index|
		#if index % 5 == 0
		#	post.title = "SPAM"
		#end
	#end

  #end

  def show
# #19 find post with id params passed to show and assign it to @post
	@post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
  	# #7 create instance var, @post then assign it an empty post returned by Post.new
  	@post = Post.new
  end

  def create 
  	# #9 call Podt.new to create new instance of Post
  	@post = Post.new
  	@post.title = params[:post][:title]
  	@post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])

    @post.topic = @topic

  	# #10 is save is successful display so, using flash[:notice] and redirect 
  	# the user to the route generated by @post. redirecting @post directs user 
  	#to the posts show view.
  	if @post.save
  	# #11 assign value to flash[:notice]. flash hash allows for passing of temp
  	#values between actions.  any value placed in flash will be ava. in the next 
  	#action and then deleted
  		flash[:notice] = "Post was saved."
  		redirect_to [@topic, @post]
  	else
  	# #12 if save to Post db is unsuccessful display message and render new view again
  		flash.now[:alert] = "There was an error saving the post. Please try again."
  		render :new
  	end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update 
    @post = Post.find(params[:id])
    @post.title = params[:post][:title] 
    @post.body = params[:post][:body]

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit 
    end
  end

  def destroy
    @post = Post.find(params[:id])
# #8 call destroy on @post. If successful set flash message and redirect the user to the posts index view
# if it fails then redirect the user to the show view using render :show
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end 
end
